In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import pandas as pd
import random as rd

In [2]:
import sys
sys.version

'3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]'

In [7]:
x = np.array([1, 2, 3, 4, 5])
y = x * 2 + 1

# 학습 구조 모델링
model = Sequential()
model.add(Dense(1, input_shape=(1,)))
model.compile('SGD', 'mse')

# 학습 수행
model.fit(x, y, epochs=100, verbose=0) #verbose 학습진행여부

# 평가
print('y:', y, ',predict:', model.predict(x).flatten())


y: [ 3  5  7  9 11] ,predict: [ 2.6901238  4.808836   6.927548   9.04626   11.164971 ]


In [22]:
a=np.full((12,12),95)
a[4:8,4:8] = 99
print(a)
df = pd.DataFrame(a)
print(df)

[[95 95 95 95 95 95 95 95 95 95 95 95]
 [95 95 95 95 95 95 95 95 95 95 95 95]
 [95 95 95 95 95 95 95 95 95 95 95 95]
 [95 95 95 95 95 95 95 95 95 95 95 95]
 [95 95 95 95 99 99 99 99 95 95 95 95]
 [95 95 95 95 99 99 99 99 95 95 95 95]
 [95 95 95 95 99 99 99 99 95 95 95 95]
 [95 95 95 95 99 99 99 99 95 95 95 95]
 [95 95 95 95 95 95 95 95 95 95 95 95]
 [95 95 95 95 95 95 95 95 95 95 95 95]
 [95 95 95 95 95 95 95 95 95 95 95 95]
 [95 95 95 95 95 95 95 95 95 95 95 95]]
    0   1   2   3   4   5   6   7   8   9   10  11
0   95  95  95  95  95  95  95  95  95  95  95  95
1   95  95  95  95  95  95  95  95  95  95  95  95
2   95  95  95  95  95  95  95  95  95  95  95  95
3   95  95  95  95  95  95  95  95  95  95  95  95
4   95  95  95  95  99  99  99  99  95  95  95  95
5   95  95  95  95  99  99  99  99  95  95  95  95
6   95  95  95  95  99  99  99  99  95  95  95  95
7   95  95  95  95  99  99  99  99  95  95  95  95
8   95  95  95  95  95  95  95  95  95  95  95  95
9   95  95  95  95  9

In [29]:
a= 0111000111111
print(type(a))

SyntaxError: invalid token (<ipython-input-29-f1783ef3210c>, line 1)

In [41]:
print(rd.randint(1,12))
input_xy_list=[]

3


In [ ]:

while True:
    x = rd.randint(1,12)
    y = rd.randint(1,12)
    if x > 4 and x <9 and y >4 and y<9:
        pass
    elif (x,y) not in input_xy_list:
        input_xy_list.append((x,y))
        break
print(input_xy_list)